In [27]:
import pandas as pd

In [3]:
pd.__version__

'3.0.2'

In [4]:
#设置输出最多为10行
pd.options.display.max_rows = 10

In [6]:
#设置输出最多列
pd.options.display.max_columns = 10

In [7]:
#series对象创建,一维数组
data = pd.Series([1,2,3,4,5,6,7,8,9])

In [8]:
#获取索引index，数据values
print(data.index)
print(data.values)

RangeIndex(start=0, stop=9, step=1)
[1 2 3 4 5 6 7 8 9]

In [9]:
#指定索引
data = pd.Series([1,2,3,4],index=['a','b','c','d'])
data

a    1
b    2
c    3
d    4
dtype: int64

In [10]:
#是呀list指定index
data = pd.Series([1,2,3,4],index=list('abcd'))
data

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
#传入字典创建
data = {'name':'张三','age':23,'sex':'male'}
data

{'name': '张三', 'age': 23, 'sex': 'male'}

In [16]:
#字典创建，并指定index
pd.Series(data,index=['name','age'])

name    张三
age     23
dtype: object

In [19]:
#创建DataFrame对象，传入两个Series对象作为字典的值
p_dict={'name':'张三','age':23,'sex':'male'}
a_dict={'name':'王五','age':27,'sex':'male'}
p_series=pd.Series(p_dict)
a_series=pd.Series(a_dict)
p_series
a_series
#将series对象作为字典的值传入pd.DataFrame
df = pd.DataFrame({'area':a_series,'population':p_series})
df

      area population
name    王五         张三
age     27         23
sex   male       male

In [22]:
df.index
df.values
df.columns

Index(['area', 'population'], dtype='str')

In [35]:
#传入二维数组
import numpy as np
pd.DataFrame(np.random.randint(10,size=(3,4)),index=list('abc'),columns=list('ABCD'))

   A  B  C  D
a  8  5  9  6
b  2  1  6  0
c  0  0  0  9

In [36]:
pd.DataFrame(p_series,columns=['population'])

     population
name         张三
age          23
sex        male